ENGLISH = "eng"
FRENCH = "fr"
ESPAGNOL = "esp"
ARAB = "ara"

LANGUAGES = [ENGLISH, FRENCH, ESPAGNOL, ARAB]

TRANS_ENGLISH = "en-US"
TRANS_FRENCH = "fr-FR"
TRANS_ESPAGNOL = "es-ES"
TRANS_ARAB = "ar-DZ"

TRANS_LANGUAGES = [TRANS_ENGLISH, TRANS_FRENCH, TRANS_ESPAGNOL, TRANS_ARAB]

TRAD_ENGLISH = "english"
TRAD_FRENCH = "french"
TRAD_ESPAGNOL = "spanish"
TRAD_ARAB = "arabic"

TRAD_LANGUAGES = [TRAD_ENGLISH, TRAD_FRENCH, TRAD_ESPAGNOL, TRAD_ARAB]

TRANS = "trans"
TRAD = "trad"

LANGUAGES_MATCHER = {}

for i in range (0, len(TRAD_LANGUAGES), 1):
    LANGUAGES_MATCHER[LANGUAGES[i]] = {TRANS : TRANS_LANGUAGES[i], TRAD : TRAD_LANGUAGES[i]}
