ENGLISH = "eng"
FRENCH = "fr"
ESPAGNOL = "esp"
ARAB = "ara"

LANGUAGES = [ENGLISH, FRENCH, ESPAGNOL, ARAB]

TRANS_ENGLISH = "en-US"
TRANS_FRENCH = "fr-FR"
TRANS_SPANISH = "es-ES"
TRANS_ARAB = "ar-DZ"

TRANS_LANGUAGES = [TRANS_ENGLISH, TRANS_FRENCH, TRANS_SPANISH, TRANS_ARAB]

TRAD_ENGLISH = "english"
TRAD_FRENCH = "french"
TRAD_SPANISH = "spanish"
TRAD_ARAB = "arabic"

TRAD_LANGUAGES = [TRAD_ENGLISH, TRAD_FRENCH, TRAD_SPANISH, TRAD_ARAB]

TRANS = "trans"
TRAD = "trad"

LANGUAGES_MATCHER = {}

for i in range (0, len(TRAD_LANGUAGES), 1):
    LANGUAGES_MATCHER[LANGUAGES[i]] = {TRANS : TRANS_LANGUAGES[i], TRAD : TRAD_LANGUAGES[i]}

REVERSE_MATCHER = {TRAD_ENGLISH: ENGLISH, TRAD_FRENCH: FRENCH, TRAD_SPANISH: ESPAGNOL, TRAD_ARAB: ARAB}

for i in range (0, len(TRAD_LANGUAGES), 1):
    LANGUAGES_MATCHER[TRAD_LANGUAGES[i]] = LANGUAGES[i]
    print(LANGUAGES_MATCHER)
